# Generated by Django 3.0.8 on 2020-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('flour', models.FloatField()),
                ('water', models.FloatField()),
                ('sourdough', models.FloatField()),
                ('salt', models.FloatField()),
            ],
        ),
    ]
